# Generated by Django 4.0.1 on 2022-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('TA', 'Танки'), ('HI', 'Хилы'), ('DD', 'ДД'), ('ME', 'Торговцы'), ('GU', 'Гилдмастеры'), ('QU', 'Квестгиверы'), ('SM', 'Кузнецы'), ('TN', 'Кожевники'), ('PO', 'Зельевары'), ('SP', 'Мастера заклинаний')], max_length=2),
        ),
    ]
