# Generated by Django 4.0.1 on 2022-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_approved',
            field=models.BooleanField(default=False),
        ),
    ]
