# Generated by Django 4.0.1 on 2022-03-15 11:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_reply_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
